service: ts-serverless-nextjs
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
plugins:
  - serverless-nextjs-plugin
custom:
  name: ts-serverless-nextjs
  serverless-nextjs:
    assetsBucketName: "ts-serverless-nextjs-${self:provider.stage}"
    cloudFront: true
package:
  exclude:
    - ./**